[package]
name = "EasyProxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pemfile = "1"
log = "0.4"
env_logger = "0.11"
base64 = "0.21"
dotenvy = "0.15"
