name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build release binary
        run: cargo build --verbose --release
      - name: Package artifacts
        run: |
          mkdir -p dist
          cp target/release/EasyProxy dist/
          cd dist
          tar czf EasyProxy-${{ github.ref_name }}-linux-amd64.tar.gz EasyProxy
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EasyProxy-${{ github.ref_name }}
          path: dist/EasyProxy-${{ github.ref_name }}-linux-amd64.tar.gz
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/EasyProxy-${{ github.ref_name }}-linux-amd64.tar.gz
